# Generated by Django 2.1.8 on 2019-04-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190424_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
