# Generated by Django 2.1.8 on 2019-05-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_testpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
