# Generated by Django 2.1.8 on 2019-05-07 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_articlepage_available_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='author',
        ),
    ]
