# Generated by Django 2.1.8 on 2019-05-13 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190513_1247'),
        ('articles', '0009_auto_20190507_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.People'),
        ),
    ]
