version: '3.5'

services:

### App Container ######################################

    api:
        container_name: wagtail_angular_api
        build:
            context: ./docker/api
            dockerfile: Dockerfile
        volumes:
            - .:/usr/src/app
        ports:
            - "8083:8000"
        restart: always
        logging:
            driver: "json-file"
            options:
                max-size: "1m"
                max-file: "3"
