# Generated by Django 2.1.8 on 2019-05-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190426_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
