# Generated by Django 2.1.8 on 2019-05-14 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_auto_20190507_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.People'),
        ),
    ]
